# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Projects @ ARIN
email: arin-tech-discuss@arin.net
description: > # this means to ignore newlines until "baseurl:"
  Open source and public code created by the American Registry for
  Internet Numbers (ARIN), and other related non-ARIN projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://projects.arin.net" # the base hostname & protocol for your site
twitter_username: teamarin
github_username:  arineng
permalink: pretty

# Build settings
markdown: kramdown
kramdown:
  input: GFM
